//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERDProduct.Resource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Ammount { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> Reserv { get; set; }
        public int IdCategory { get; set; }
        public int ProductListType { get; set; }
    
        public virtual CategoryProduct CategoryProduct { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
